name: red-tetris

services:
  app:
    build:
      context: .
      dockerfile: server/Dockerfile
      target: prod
    env_file:
      - path: ../.env
        required: false
    environment:
      PORT: 3000
    ports:
      - "${PORT:-3000}:3000"
    restart: unless-stopped
